/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/diagnose`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/analytics` | `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/signin`; params?: Router.UnknownInputParams; } | { pathname: `/signin/passphrase`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step2`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step3`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step4`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step5`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step6`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step7`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step8`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step9`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/diagnose`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/analytics` | `/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/signin/passphrase`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/step2`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/step3`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/step4`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/step5`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/step6`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/step7`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/step8`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/step9`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/diagnose${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/analytics${`?${string}` | `#${string}` | ''}` | `/analytics${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/signin${`?${string}` | `#${string}` | ''}` | `/signin/passphrase${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/signup/step2${`?${string}` | `#${string}` | ''}` | `/signup/step3${`?${string}` | `#${string}` | ''}` | `/signup/step4${`?${string}` | `#${string}` | ''}` | `/signup/step5${`?${string}` | `#${string}` | ''}` | `/signup/step6${`?${string}` | `#${string}` | ''}` | `/signup/step7${`?${string}` | `#${string}` | ''}` | `/signup/step8${`?${string}` | `#${string}` | ''}` | `/signup/step9${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/diagnose`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/analytics` | `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/signin`; params?: Router.UnknownInputParams; } | { pathname: `/signin/passphrase`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step2`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step3`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step4`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step5`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step6`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step7`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step8`; params?: Router.UnknownInputParams; } | { pathname: `/signup/step9`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
